export enum Route {
  HOME = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  DASHBOARD = "/dashboard",
  AUTHOR = "/author",
  AUTHOR_DETAIL = "/author/",
  AUTHOR_CREATE = "/author/create",
  AUTHOR_EDIT = "/author/edit/:id",
  BOOK = "/book",
  BOOK_CREATE = "/book/create",
  BOOK_EDIT = "/book/edit/:id",
  CATEGORY = "/category",
  CATEGORY_CREATE = "/category/create",
  CATEGORY_EDIT = "/category/edit/:id",
  USER = "/user",
  USER_CREATE = "/user/create",
  USER_EDIT = "/user/edit/:id",
  BORROWING = "/borrowing",
  BORROWING_CREATE = "/borrowing/create",
  BORROWING_EDIT = "/borrowing/edit/:id",
  SETTINGS = "/settings",
  PROFILE = "/profile",
  NOT_FOUND = "/404",
  FORBIDDEN = "/403",
  SERVER_ERROR = "/500",
}
