import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ReactQueryProvider } from "@/components/providers/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AntdRegistry>
            <Layout>{children}</Layout>
          </AntdRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
